name: Linters

on: [pull_request]

jobs:
  validate-commits:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Run Commitsar
        uses: docker://aevea/commitsar:0.20.2

  golangci-lint:
    name: runner / golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
      - name: golangci-lint
        uses: docker://reviewdog/action-golangci-lint@sha256:9f8af9633d7a14d2100936693dc609249e13c29a352ce88fdc8a3d0aaadd8b26
        with:
          github_token: ${{ secrets.github_token }}
